### ISSUE TITLE
Incorrect sector shift while removing USBC sector

### ISSUE THREAD

**Issue by jaanrebane** [DRCRecoveryData/usbc-sector-patcher#2]
This change worked for me:

`for i in range(2, cmd_len+1):`
changed to
`for i in range(1, cmd_len+1):`

in method_1.py

**Comment by DRCRecoveryData** [comment]
i don't see difference from original and patched can you provide for me difference changed?

**Comment by jaanrebane** [comment]
Your last code is working the same way as last code in my repo, I also don't see a difference any more.

**Comment by DRCRecoveryData** [comment]
> Your last code is working the same way as last code in my repo, I also don't see a difference any more.

can you explain from original img file and patched img file? how they difference after patched?

**Comment by jaanrebane** [comment]
I don't think I understand you, but I will try.

With my GoPro bad img file, after I run the `method_1.py` script that uses `for i in range(2, cmd_len+1):` then I can't do File Undelete in `testdisk image.img`. If I run the script with `for i in range(1, cmd_len+1):`, the File Undelete lists the files (it works). File Undelete in Testdisk (`testdisk image.img`): Proceed - Intel PC Partition - Advanced - Undelete (look down).

Then, comparing the `range(2` (=1st case) and `range(1` (=2nd case) image files with `xxd` and `diff`, I can see at hex offset 0x400000 there are just 0x00 in the 1st case, but data in the second case (WIN...FAT32). Some random data moved from 0x4C7C00 to 0x863E00, root folder has 0xC00200 instead of 0xC00000. Folder data in offset 0xC40000 is missing first 512 bytes. And some other minor differences.

I don't know why exactly it works, but the file that was created by `range(1` version of the script makes a lot more sense (good blocks in reasonable places).

These comments are based only modifying `method_1.py` based on old commit `3b403b6b8624d869e982c93d25f435fb65d2f226` (20 Feb 2023).
