### ISSUE TITLE
Script modifies the original file

### ISSUE THREAD

**Issue by jaanrebane** [DRCRecoveryData/usbc-sector-patcher#3]
I am testing the script and the original file (that is opened with python) is also modified, in addition to the Patched folder version of the file. This should be changed.

**Comment by DRCRecoveryData** [comment]
> I am testing the script and the original file (that is opened with python) is also modified, in addition to the Patched folder version of the file. This should be changed.

If code error or working, could you give me feedback to update it?

**Comment by jaanrebane** [comment]
I don't know how to fix the issue that the original disk image file is also modified. So, a backup of the disk image needs to be made first.

But I managed to recover most of a disk image using the method_1.py in my pull request. Modify this file in your git according to your needs.

**Comment by DRCRecoveryData** [comment]
> I don't know how to fix the issue that the original disk image file is also modified. So, a backup of the disk image needs to be made first.
> 
> 
> 
> But I managed to recover most of a disk image using the method_1.py in my pull request. Modify this file in your git according to your needs.

Could you upload your img file backup from your usb/sdcard?

**Comment by jaanrebane** [comment]
I added a 30MB sample (first 30MB of a 32GB image) to my github repo. Does not contain anything sensitive, but might delete later. This can be tested with Testdisk before and after running method_1.py.
See this link:
https://github.com/jaanrebane/sampledata

**Comment by jaanrebane** [comment]
It looks like both method_1.py and method_2.py do not modify the original file any more.

For recovery procedure of a GoPro SD card, I also had to learn quite a bit about FAT filesystem and I ended up manually editing/moving data around using dd and other Linux tools. My end result that helped me to recover all good quality videos is in the repo above (sampledata).

If you would like to have whole 32GB images (bad and fixed) to play around with, please contact me directly (my contact is in the sampledata repo, link above this post).
